# Generated by Django 4.2 on 2024-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Загрузите файл', upload_to='files_media', verbose_name='Файл'),
        ),
    ]
